BASE_URL = "https://secure.runescape.com/m=hiscore/index_lite.ws?player={username}"

HS_DICT= {
    0: "Overall",
    1: "Attack",
    2: "Defence",
    3: "Strength",
    4: "Constitution",
    5: "Ranged",
    6: "Prayer",
    7: "Magic",
    8: "Cooking",
    9: "Woodcutting",
    10: "Fletching",
    11: "Fishing",
    12: "Firemaking",
    13: "Crafting",
    14: "Smithing",
    15: "Mining",
    16: "Herblore",
    17: "Agility",
    18: "Thieving",
    19: "Slayer",
    20: "Farming",
    21: "Runecrafting",
    22: "Hunter",
    23: "Construction",
    24: "Summoning",
    25: "Dungeoneering",
    26: "Divination",
    27: "Invention",
    28: "Archaeology",
    29: "Necromancy",
    30: "Bounty Hunter",
    31: "B.H. Rogues",
    32: "Dominion Tower",
    33: "The Crucible",
    34: "Castle Wars games",
    35: "B.A. Attackers",
    36: "B.A. Defenders",
    37: "B.A. Collectors",
    38: "B.A. Healers",
    39: "Duel Tournament",
    40: "Mobilising Armies",
    41: "Conquest",
    42: "Fist of Guthix",
    43: "GG: Athletics",
    44: "GG: Resource Race",
    45: "WE2: Armadyl Lifetime Contribution",
    46: "WE2: Bandos Lifetime Contribution",
    47: "WE2: Armadyl PvP kills",
    48: "WE2: Bandos PvP kills",
    49: "Heist Guard Level",
    50: "Heist Robber Level",
    51: "CFP: 5 game average",
    52: "AF15: Cow Tipping",
    53: "AF15: Rats killed after the miniquest",
    54: "RuneScore",
    55: "Clue Scrolls Easy",
    56: "Clue Scrolls Medium",
    57: "Clue Scrolls Hard",
    58: "Clue Scrolls Elite",
    59: "Clue Scrolls Master"
}